name: CI & Deploy (S3 + CloudFront)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write   # for OIDC
  contents: read

env:
  NODE_VERSION: 20
  AWS_REGION: ap-south-1
  S3_BUCKET: zenteq-in-site            # <-- set your bucket name
  CLOUDFRONT_DISTRIBUTION_ID: EXXXXXXXXXXXX # <-- set your distribution id

jobs:
  test_build:
    name: Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: out
          if-no-files-found: error
          retention-days: 7

  deploy:
    name: Deploy to S3 + Invalidate CloudFront
    needs: test_build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: site

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_OIDC_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync to S3
        run: |
          aws s3 sync site/ s3://${{ env.S3_BUCKET }} \
            --delete \
            --cache-control max-age=31536000,public \
            --metadata-directive REPLACE
        # For index.html / assets cache split, you can do targeted headers if needed.

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

      - name: Post summary
        run: |
          echo "✅ Deployed to s3://${{ env.S3_BUCKET }} and invalidated CloudFront ${{ env.CLOUDFRONT_DISTRIBUTION_ID }}" >> $GITHUB_STEP_SUMMARY
